/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.BaseResponse;
import io.swagger.model.BuildInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-23T05:55:13.551Z")

@Api(value = "workflowadapter", description = "the workflowadapter API")
public interface WorkflowadapterApi {

    @ApiOperation(value = "Inovke the jenkins vnf onboarding job", nickname = "workflowadapterVnfonboardPut", notes = "Inovke the jenkins vnf onboarding job", response = BaseResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Onboarding status", response = BaseResponse.class) })
    @RequestMapping(value = "/workflowadapter/vnfonboard",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<BaseResponse> workflowadapterVnfonboardPut(@NotNull @ApiParam(value = "Execution jenkins job id", required = true) @Valid @RequestParam(value = "uid", required = true) String uid);


    @ApiOperation(value = "Does the prevalidation for VNF", nickname = "workflowadapterVnfprevalidatePost", notes = "Does the prevalidation for VNF", response = BuildInfo.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "VNF Prevalidation status", response = BuildInfo.class) })
    @RequestMapping(value = "/workflowadapter/vnfprevalidate",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<BuildInfo> workflowadapterVnfprevalidatePost(@NotNull @ApiParam(value = "Execution jenkins job id12", required = true) @Valid @RequestParam(value = "uid", required = true) String uid);

}
